// <auto-generated />
using System;
using MessageBoard.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MessageBoard.Migrations
{
    [DbContext(typeof(MessageBoardContext))]
    [Migration("20240603223400_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MessageBoard.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<string>("Group")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PostTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("user_name")
                        .HasColumnType("longtext");

                    b.HasKey("MessageId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            MessageId = 1,
                            Content = "What's up",
                            Group = "Video",
                            PostTime = new DateTime(2024, 6, 3, 15, 34, 0, 424, DateTimeKind.Local).AddTicks(491),
                            user_name = "jon"
                        },
                        new
                        {
                            MessageId = 2,
                            Content = "Not much",
                            Group = "Video",
                            PostTime = new DateTime(2024, 6, 3, 15, 34, 0, 424, DateTimeKind.Local).AddTicks(524),
                            user_name = "join"
                        },
                        new
                        {
                            MessageId = 3,
                            Content = "The weather",
                            Group = "Weather",
                            PostTime = new DateTime(2024, 6, 3, 15, 34, 0, 424, DateTimeKind.Local).AddTicks(526),
                            user_name = "Mr.Weather"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
